const cutsceneSystem={active:false,dialogues:[],idx:0,name:'',text:'',shown:'',ci:0,tTimer:0,bg:'dark',chars:[],fade:1,fading:true,onComplete:null,
    start(d,on){this.active=true;this.dialogues=d;this.idx=0;this.fade=1;this.fading=true;this.onComplete=on;this._load();},
    _load(){if(this.idx>=this.dialogues.length){this.active=false;if(this.onComplete)this.onComplete();return;}const l=this.dialogues[this.idx];this.name=l.name||'';this.text=l.text||'';this.shown='';this.ci=0;this.bg=l.bg||this.bg;this.chars=l.chars||this.chars;},
    advance(){if(this.ci<this.text.length){this.shown=this.text;this.ci=this.text.length;return;}this.idx++;this._load();},
    skip(){this.active=false;if(this.onComplete)this.onComplete();},
    update(){if(!this.active)return;if(this.fading){this.fade-=.03;if(this.fade<=0){this.fade=0;this.fading=false;}}this.tTimer++;if(this.tTimer>=2&&this.ci<this.text.length){this.tTimer=0;this.ci++;this.shown=this.text.substring(0,this.ci);}},
    render(ctx,W,H){if(!this.active)return;
        if(this.bg==='city'){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#1a1a3a');g.addColorStop(1,'#0a0a1a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#111';for(let i=0;i<15;i++){const bw=W/15,bh=100+Math.sin(i*2.1)*80;ctx.fillRect(i*bw,H*.4-bh,bw-3,bh+H);}ctx.fillStyle='#222';ctx.fillRect(0,H*.4,W,H*.6);}
        else if(this.bg==='car'){ctx.fillStyle='#1a1a2a';ctx.fillRect(0,0,W,H);ctx.fillStyle='#222';ctx.fillRect(W*.1,H*.6,W*.8,H*.4);}
        else{ctx.fillStyle='#0a0a0a';ctx.fillRect(0,0,W,H);}
        this.chars.forEach(ch=>{const x=ch.x*W,y=H*.35,sc=ch.scale||1;ctx.save();ctx.translate(x,y);ctx.scale(sc,sc);ctx.fillStyle=ch.color||'#444';ctx.fillRect(-20,-10,40,60);ctx.fillStyle=ch.skin||'#fca';ctx.beginPath();ctx.arc(0,-25,18,0,6.28);ctx.fill();ctx.fillStyle=ch.hair||'#333';ctx.beginPath();ctx.arc(0,-30,16,Math.PI,0);ctx.fill();ctx.fillStyle='#fff';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText(ch.label||'',0,75);ctx.restore();});
        const bH=150,bY=H-bH-30,bX=40,bW=W-80;ctx.fillStyle='rgba(0,0,0,.8)';ctx.fillRect(bX+4,bY+4,bW,bH);ctx.fillStyle='rgba(10,10,30,.92)';ctx.fillRect(bX,bY,bW,bH);ctx.strokeStyle='#f80';ctx.lineWidth=2;ctx.strokeRect(bX,bY,bW,bH);
        if(this.name){ctx.fillStyle='#f80';ctx.font='bold 20px Arial';ctx.textAlign='left';ctx.fillText(this.name,bX+20,bY+30);}
        ctx.fillStyle='#eee';ctx.font='18px Arial';ctx.textAlign='left';const words=this.shown.split(' ');let line='',ly=bY+65;const maxW=bW-40;words.forEach(w=>{const t=line+w+' ';if(ctx.measureText(t).width>maxW){ctx.fillText(line,bX+20,ly);line=w+' ';ly+=26;}else line=t;});ctx.fillText(line,bX+20,ly);
        if(this.ci>=this.text.length){if(Math.sin(Date.now()*.005)>0){ctx.fillStyle='#f80';ctx.font='16px Arial';ctx.textAlign='right';ctx.fillText('▼ ENTER / SPACE',bX+bW-20,bY+bH-15);}}
        ctx.fillStyle='#666';ctx.font='12px Arial';ctx.textAlign='right';ctx.fillText(`${this.idx+1} / ${this.dialogues.length}`,bX+bW-20,bY-10);ctx.textAlign='left';ctx.fillText('ESC — пропустить',bX+20,bY-10);
        if(this.fade>0){ctx.fillStyle=`rgba(0,0,0,${this.fade})`;ctx.fillRect(0,0,W,H);}}};

const missionMarker={x:0,y:0,active:false,kind:'trigger'};
const M={phase:'idle',objectives:[],cur:0,reward:500};
const DIALOGUE_1=[
    {name:'',text:'Лос-Анджелес. 2026 год. Город, который никогда не спит и никогда не прощает.',bg:'city',chars:[]},
    {name:'',text:'Ты только что вышел из тюрьмы. Пять лет за ограбление, где всё пошло не по плану.',bg:'dark',chars:[]},
    {name:'🧔 Виктор',text:'О! Живой! Иди сюда, брат. Мне нужен человек за рулём.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'🧔 Виктор',text:'Угонишь тачку, любую. Доедешь до моей точки. Плачу пятьсот баксов.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'🧔 Виктор',text:'Не стреляй, не сбивай копов — и звёзд не будет. Добро пожаловать домой, брат.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'',text:'▶ ЦЕЛЬ: укради машину и доедь до жёлтой метки.',bg:'dark',chars:[]}];
const DIALOGUE_DONE=[
    {name:'🧔 Виктор',text:'Доехал! Вот пятьсот баксов. Ты мне нравишься, брат.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'🧔 Виктор',text:'Отдохни. Когда понадобишься — я найду тебя. Всегда.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'',text:'🔓 СВОБОДНЫЙ РЕЖИМ! Исследуй город, магазины, остров на севере.',bg:'dark',chars:[]}];
function initMission1Marker(){M.phase='trigger';M.objectives=[];M.cur=0;missionMarker.x=8*BLOCK*TILE+TILE*1.5;missionMarker.y=7*BLOCK*TILE+TILE*1.5;missionMarker.active=true;missionMarker.kind='trigger';}
function resetM1(){M.phase='active';M.objectives=[{text:'Угони машину (подойди и нажми F)',done:false},{text:'Доедь до жёлтой метки Виктора',done:false}];M.cur=0;missionMarker.x=9*BLOCK*TILE+TILE*1.5;missionMarker.y=9*BLOCK*TILE+TILE*1.5;missionMarker.active=true;missionMarker.kind='goal';}
function updateMission(){if(cutsceneSystem.active){cutsceneSystem.update();return;}
    if(M.phase==='trigger'&&missionMarker.active&&dist(player,missionMarker)<55){missionMarker.active=false;M.phase='cutscene';playSFX('mission');cutsceneSystem.start(DIALOGUE_1,()=>{resetM1();showMission('📋 Миссия: Первая поездка',3000);});}
    if(M.phase==='active'){if(M.cur===0&&player.inVehicle){M.objectives[0].done=true;M.cur=1;showMission('✅ Тачка угнана! Гони к метке!',2500);playSFX('select');}
        if(M.cur===1&&missionMarker.active&&dist(player,missionMarker)<55){M.objectives[1].done=true;M.phase='done';missionMarker.active=false;player.money+=M.reward;playSFX('pickup');showMessage('МИССИЯ ВЫПОЛНЕНА!',3000);showMission('+$'+M.reward,3000);setTimeout(()=>cutsceneSystem.start(DIALOGUE_DONE,()=>{M.phase='free';}),3200);}}}
function arrowTo(ctx,W,H,tx,ty){const d=dist(player,{x:tx,y:ty});if(d<300)return;const a=angleTo(player,{x:tx,y:ty});const ax=W/2+Math.cos(a)*90,ay=H/2+Math.sin(a)*90;ctx.save();ctx.translate(ax,ay);ctx.rotate(a);ctx.fillStyle='rgba(255,255,0,.8)';ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-9,-9);ctx.lineTo(-9,9);ctx.fill();ctx.restore();ctx.fillStyle='#ff0';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(Math.round(d)+'м',ax,ay-14);}
function renderMissionHUD(ctx,W,H){if(cutsceneSystem.active){cutsceneSystem.render(ctx,W,H);return;}
    if(M.phase==='trigger'&&missionMarker.active){ctx.save();ctx.translate(-camera.x,-camera.y);const p=Math.sin(gameTime*.08)*5;ctx.strokeStyle='#ff0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,45+p,0,6.28);ctx.stroke();ctx.globalAlpha=.12;ctx.fillStyle='#ff0';ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,45+p,0,6.28);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#ff0';ctx.font='bold 28px Arial';ctx.textAlign='center';ctx.fillText('V',missionMarker.x,missionMarker.y+10);if(dist(player,missionMarker)<120){ctx.fillStyle='#fff';ctx.font='14px Arial';ctx.fillText('Подойди ближе',missionMarker.x,missionMarker.y-55);}ctx.restore();arrowTo(ctx,W,H,missionMarker.x,missionMarker.y);return;}
    if(M.phase==='active'){const pX=W-330,pY=130,pW=310;ctx.fillStyle='rgba(0,0,0,.6)';ctx.fillRect(pX,pY,pW,30+M.objectives.length*28);ctx.strokeStyle='rgba(255,136,0,.5)';ctx.lineWidth=1;ctx.strokeRect(pX,pY,pW,30+M.objectives.length*28);ctx.fillStyle='#f80';ctx.font='bold 14px Arial';ctx.textAlign='left';ctx.fillText('📋 Первая поездка',pX+10,pY+20);M.objectives.forEach((o,i)=>{const y=pY+45+i*28;if(o.done){ctx.fillStyle='#4c4';ctx.font='13px Arial';ctx.fillText('✅ '+o.text,pX+10,y);}else if(i===M.cur){ctx.fillStyle='#ff0';ctx.font='bold 13px Arial';ctx.fillText('▶ '+o.text,pX+10,y);}else{ctx.fillStyle='#888';ctx.font='13px Arial';ctx.fillText('○ '+o.text,pX+10,y);}});
        if(M.cur===1&&missionMarker.active){ctx.save();ctx.translate(-camera.x,-camera.y);const p=Math.sin(gameTime*.08)*5;ctx.strokeStyle='#ff0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,50+p,0,6.28);ctx.stroke();ctx.globalAlpha=.1;ctx.fillStyle='#ff0';ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,50+p,0,6.28);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#ff0';ctx.beginPath();ctx.moveTo(missionMarker.x,missionMarker.y-55-p);ctx.lineTo(missionMarker.x-10,missionMarker.y-70-p);ctx.lineTo(missionMarker.x+10,missionMarker.y-70-p);ctx.fill();const d=Math.round(dist(player,missionMarker));ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(d+'м',missionMarker.x,missionMarker.y-75-p);ctx.restore();arrowTo(ctx,W,H,missionMarker.x,missionMarker.y);}}
    if(M.phase==='free'){ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(W-230,130,210,30);ctx.fillStyle='#4c4';ctx.font='bold 13px Arial';ctx.textAlign='left';ctx.fillText('🔓 Свободный режим',W-220,150);}}
window.missionRestarters=window.missionRestarters||[];
window.missionRestarters.push(()=>{if(M.phase==='active'){resetM1();showMission('🔁 Миссия 1 начата заново',2000);}});
window.cutsceneSystem=cutsceneSystem;window.missionMarker=missionMarker;window.M=M;
window.initMission1Marker=initMission1Marker;window.updateMission=updateMission;window.renderMissionHUD=renderMissionHUD;