const m3Enemies=[];let m3Hostage=null;const M3={phase:'idle',objectives:[],cur:0,reward:1500};
const M3_TRIGGER={x:7*BLOCK*TILE+TILE*1.5,y:9*BLOCK*TILE+TILE*1.5};
const M3_DISTRICT={x:10*BLOCK*TILE+TILE*1.5,y:10*BLOCK*TILE+TILE*1.5};
const D3_START=[
{name:'🧔 Виктор',text:'Брат... беда. Банда Долли взяла заложницу. Девочку. В районе на востоке.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
{name:'🧔 Виктор',text:'Пятеро вооружены. НЕ ЗАДЕНЬ девочку. Привези её живой. Умоляю.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
{name:'',text:'▶ ЦЕЛЬ: доедь до района, убей банду, НЕ стреляй в заложницу, подойди к ней.',bg:'dark',chars:[]}];
const D3_DONE=[
{name:'👧 Девочка',text:'*плачет* Спасибо, дядя... Я так боялась...',bg:'city',chars:[{x:.5,color:'#d6a',skin:'#fca',hair:'#a52',label:'Девочка',scale:1.1}]},
{name:'🧔 Виктор',text:'Ты спас мне душу, брат. Полторы тысячи. Ты теперь семья.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
{name:'',text:'🔓 МИССИЯ 3 ПРОЙДЕНА! Ты — легенда района.',bg:'dark',chars:[]}];
function _blood3(x,y){if(typeof addBlood==='function')addBlood(x,y);}
function spawnM3(){m3Enemies.length=0;for(let i=0;i<5;i++){const a=(i/5)*6.28+rand(-.3,.3),r=rand(90,150);let x=clamp(M3_DISTRICT.x+Math.cos(a)*r,50,WORLD_W-50),y=clamp(M3_DISTRICT.y+Math.sin(a)*r,50,WORLD_H-50);m3Enemies.push({x,y,angle:0,hp:90,maxHp:90,alive:true,shootT:rand(30,80)});}m3Hostage={x:M3_DISTRICT.x,y:M3_DISTRICT.y,alive:true};}
function resetM3(msg){spawnM3();M3.phase='active';M3.objectives=[{text:'Доедь до района банды',done:false},{text:'Убей банду, не тронь заложницу (0/5)',done:false},{text:'Подойди к девочке',done:false}];M3.cur=0;missionMarker.x=M3_DISTRICT.x;missionMarker.y=M3_DISTRICT.y;missionMarker.active=true;missionMarker.kind='goal3';if(msg){showMessage(msg,3000);showMission('🔁 Миссия 3 начата заново',2500);}}
function arrow3(ctx,W,H,tx,ty){const d=dist(player,{x:tx,y:ty});if(d<300)return;const a=angleTo(player,{x:tx,y:ty});const ax=W/2+Math.cos(a)*90,ay=H/2+Math.sin(a)*90;ctx.save();ctx.translate(ax,ay);ctx.rotate(a);ctx.fillStyle='rgba(255,120,200,.85)';ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-9,-9);ctx.lineTo(-9,9);ctx.fill();ctx.restore();ctx.fillStyle='#f8c';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(Math.round(d)+'м',ax,ay-14);}
function updateMission3(){if(window.cutsceneSystem&&window.cutsceneSystem.active)return;
if(M3.phase==='idle'&&window.M2&&window.M2.phase==='free'){M3.phase='trigger';missionMarker.x=M3_TRIGGER.x;missionMarker.y=M3_TRIGGER.y;missionMarker.active=true;missionMarker.kind='trigger3';showMission('📞 МИССИЯ 3 — иди к розовой «3»!',4000);showMessage('📞 МИССИЯ 3: спаси девочку, найди розовую «3»',3500);}
if(M3.phase==='trigger'&&missionMarker.active&&dist(player,missionMarker)<55){missionMarker.active=false;M3.phase='cutscene';playSFX('mission');window.cutsceneSystem.start(D3_START,()=>{resetM3(null);showMission('📋 Миссия: Спасти девочку',3000);});}
if(M3.phase==='active'){
 if(M3.cur===0&&dist(player,M3_DISTRICT)<70){M3.objectives[0].done=true;M3.cur=1;spawnM3();missionMarker.active=false;showMission('⚠️ Заложница в центре! Стреляй ТОЧНО!',3000);playSFX('select');}
 if(M3.cur===1){m3Enemies.forEach(e=>{if(!e.alive)return;const d=dist(e,player);e.angle=angleTo(e,player);if(d>165){e.x+=Math.cos(e.angle)*1.2;e.y+=Math.sin(e.angle)*1.2;}else if(d<110){e.x-=Math.cos(e.angle)*.8;e.y-=Math.sin(e.angle)*.8;}if(collidesBuilding(e.x,e.y,10)){e.x-=Math.cos(e.angle)*6;e.y-=Math.sin(e.angle)*6;}e.x=clamp(e.x,0,WORLD_W);e.y=clamp(e.y,0,WORLD_H);e.shootT--;if(d<330&&e.shootT<=0){e.shootT=55+rand(0,45);shoot(e.x+Math.cos(e.angle)*14,e.y+Math.sin(e.angle)*14,e.angle+rand(-.12,.12),7,300,'police');playSFX('shoot');}});
  for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];if(b.owner!=='player')continue;if(m3Hostage&&m3Hostage.alive&&dist(b,m3Hostage)<16){bullets.splice(i,1);M3.phase='retry';showMessage('❌ Ты ранил заложницу! МИССИЯ ПРОВАЛЕНА',3000);playSFX('wasted');setTimeout(()=>resetM3('🔁 Начни миссию 3 заново'),1500);continue;}for(const e of m3Enemies){if(e.alive&&dist(b,e)<14){e.hp-=b.damage;spawnParticles(e.x,e.y,'#f00',4,2);playSFX('hit');bullets.splice(i,1);if(e.hp<=0){e.alive=false;_blood3(e.x,e.y);spawnParticles(e.x,e.y,'#a00',12,3);player.money+=20;}break;}}}
  const dead=m3Enemies.filter(e=>!e.alive).length;M3.objectives[1].text='Убей банду, не тронь заложницу ('+dead+'/'+m3Enemies.length+')';
  if(dead>=m3Enemies.length){M3.objectives[1].done=true;M3.cur=2;missionMarker.x=m3Hostage.x;missionMarker.y=m3Hostage.y;missionMarker.active=true;missionMarker.kind='goal3b';showMission('✅ Банда мертва! Подойди к девочке',2500);playSFX('select');}}
 if(M3.cur===2&&missionMarker.active&&m3Hostage&&dist(player,m3Hostage)<45){M3.objectives[2].done=true;M3.phase='done';missionMarker.active=false;player.money+=M3.reward;playSFX('pickup');showMessage('МИССИЯ ВЫПОЛНЕНА!',3000);showMission('+$'+M3.reward,3000);m3Enemies.length=0;m3Hostage=null;setTimeout(()=>window.cutsceneSystem.start(D3_DONE,()=>{M3.phase='free';}),3200);}}}
function renderMission3World(ctx,W,H){if(window.cutsceneSystem&&window.cutsceneSystem.active)return;
if(M3.phase==='trigger'&&missionMarker.active){ctx.save();ctx.translate(-camera.x,-camera.y);const p=Math.sin(gameTime*.08)*5;ctx.strokeStyle='#f8c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,45+p,0,6.28);ctx.stroke();ctx.globalAlpha=.12;ctx.fillStyle='#f8c';ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,45+p,0,6.28);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#f8c';ctx.font='bold 28px Arial';ctx.textAlign='center';ctx.fillText('3',missionMarker.x,missionMarker.y+10);if(dist(player,missionMarker)<120){ctx.fillStyle='#fff';ctx.font='14px Arial';ctx.fillText('Подойди ближе',missionMarker.x,missionMarker.y-55);}ctx.restore();arrow3(ctx,W,H,missionMarker.x,missionMarker.y);return;}
if(M3.phase==='active'){ctx.save();ctx.translate(-camera.x,-camera.y);m3Enemies.forEach(e=>{if(!e.alive)return;ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.angle);ctx.fillStyle='#722';ctx.fillRect(-6,-5,12,10);ctx.fillStyle='#dba';ctx.beginPath();ctx.arc(7,0,6,0,6.28);ctx.fill();ctx.fillStyle='#222';ctx.beginPath();ctx.arc(7,0,6,-2.2,2.2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(10,-2,13,3);ctx.restore();ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(e.x-15,e.y-18,30,4);ctx.fillStyle='#f44';ctx.fillRect(e.x-15,e.y-18,30*(e.hp/e.maxHp),4);});
 if(m3Hostage&&m3Hostage.alive){const hb=Math.sin(gameTime*.1)*3;ctx.fillStyle='#d6a';ctx.fillRect(m3Hostage.x-5,m3Hostage.y-4,10,8);ctx.fillStyle='#fca';ctx.beginPath();ctx.arc(m3Hostage.x+6,m3Hostage.y,5,0,6.28);ctx.fill();ctx.fillStyle='#a52';ctx.beginPath();ctx.arc(m3Hostage.x+6,m3Hostage.y,5,-2.2,2.2);ctx.fill();ctx.fillStyle='#f8c';ctx.font='16px Arial';ctx.textAlign='center';ctx.fillText('👧',m3Hostage.x,m3Hostage.y-16+hb);ctx.fillStyle='#fff';ctx.font='11px Arial';ctx.fillText('НЕ СТРЕЛЯЙ!',m3Hostage.x,m3Hostage.y-30);}
 if(M3.cur===1){const p=Math.sin(gameTime*.1)*4;ctx.strokeStyle='rgba(255,120,200,.5)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(M3_DISTRICT.x,M3_DISTRICT.y,140+p,0,6.28);ctx.stroke();}ctx.restore();}
if(M3.phase==='active'&&missionMarker.active){ctx.save();ctx.translate(-camera.x,-camera.y);const p=Math.sin(gameTime*.08)*5;ctx.strokeStyle='#ff0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,50+p,0,6.28);ctx.stroke();ctx.globalAlpha=.1;ctx.fillStyle='#ff0';ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,50+p,0,6.28);ctx.fill();ctx.globalAlpha=1;const d=Math.round(dist(player,missionMarker));ctx.fillStyle='#ff0';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(d+'м',missionMarker.x,missionMarker.y-55-p);ctx.restore();arrow3(ctx,W,H,missionMarker.x,missionMarker.y);}}
function renderMission3HUD(ctx,W,H){if(M3.phase!=='active')return;const pX=W-330,pY=240,pW=310;ctx.fillStyle='rgba(0,0,0,.6)';ctx.fillRect(pX,pY,pW,30+M3.objectives.length*28);ctx.strokeStyle='rgba(255,120,200,.5)';ctx.lineWidth=1;ctx.strokeRect(pX,pY,pW,30+M3.objectives.length*28);ctx.fillStyle='#f8c';ctx.font='bold 14px Arial';ctx.textAlign='left';ctx.fillText('👧 Спасти девочку',pX+10,pY+20);M3.objectives.forEach((o,i)=>{const y=pY+45+i*28;if(o.done){ctx.fillStyle='#4c4';ctx.font='13px Arial';ctx.fillText('✅ '+o.text,pX+10,y);}else if(i===M3.cur){ctx.fillStyle='#ff0';ctx.font='bold 13px Arial';ctx.fillText('▶ '+o.text,pX+10,y);}else{ctx.fillStyle='#888';ctx.font='13px Arial';ctx.fillText('○ '+o.text,pX+10,y);}});}
const _u3=window.updateMission;window.updateMission=function(){if(_u3)_u3();updateMission3();};
const _r3=window.renderMissionHUD;window.renderMissionHUD=function(c,W,H){renderMission3World(c,W,H);if(_r3)_r3(c,W,H);renderMission3HUD(c,W,H);};
window.missionRestarters=window.missionRestarters||[];
window.missionRestarters.push(()=>{if(M3.phase==='active'||M3.phase==='retry'){resetM3('💀 Провал — миссия 3 заново');}});
window.M3=M3;
