const m2Enemies=[];const M2={phase:'idle',objectives:[],cur:0,reward:1000};
const M2_TRIGGER={x:7*BLOCK*TILE+TILE*1.5,y:7*BLOCK*TILE+TILE*1.5};
const M2_WARE={x:9*BLOCK*TILE+TILE*1.5,y:8*BLOCK*TILE+TILE*1.5};
const M2_VICTOR={x:8*BLOCK*TILE+TILE*1.5,y:7*BLOCK*TILE+TILE*1.5};
const D2_START=[
    {name:'🧔 Виктор',text:'Брат, банда Долли заняла МОЙ склад. Возьми ствол и разберись.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'🧔 Виктор',text:'Пятеро. Доедь, зачисти, возвращайся. Тысяча баксов.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'',text:'▶ ЦЕЛЬ: доедь до склада и зачисти банду Долли.',bg:'dark',chars:[]}];
const D2_DONE=[
    {name:'🧔 Виктор',text:'Ты правда всех положил? Вот твоя тысяча. Ты теперь мой человек.',bg:'city',chars:[{x:.3,color:'#833',skin:'#dba',hair:'#222',label:'Виктор',scale:1.2}]},
    {name:'',text:'🔓 МИССИЯ 2 ПРОЙДЕНА! Жди следующих звонков...',bg:'dark',chars:[]}];
function spawnM2(cx,cy){m2Enemies.length=0;for(let i=0;i<5;i++){const a=(i/5)*6.28+rand(-.3,.3),r=rand(90,150);let x=clamp(cx+Math.cos(a)*r,50,WORLD_W-50),y=clamp(cy+Math.sin(a)*r,50,WORLD_H-50);m2Enemies.push({x,y,angle:0,hp:80,maxHp:80,alive:true,shootT:rand(30,80)});}}
function arrow2(ctx,W,H,tx,ty){const d=dist(player,{x:tx,y:ty});if(d<300)return;const a=angleTo(player,{x:tx,y:ty});const ax=W/2+Math.cos(a)*90,ay=H/2+Math.sin(a)*90;ctx.save();ctx.translate(ax,ay);ctx.rotate(a);ctx.fillStyle='rgba(255,80,80,.85)';ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-9,-9);ctx.lineTo(-9,9);ctx.fill();ctx.restore();ctx.fillStyle='#f66';ctx.font='12px Arial';ctx.textAlign='center';ctx.fillText(Math.round(d)+'м',ax,ay-14);}
function resetM2(){spawnM2(M2_WARE.x,M2_WARE.y);M2.phase='active';M2.objectives=[{text:'Доедь до склада банды Долли',done:false},{text:'Зачисти банду (0/5)',done:false},{text:'Вернись к Виктору',done:false}];M2.cur=0;missionMarker.x=M2_WARE.x;missionMarker.y=M2_WARE.y;missionMarker.active=true;missionMarker.kind='goal2';}
function updateMission2(){if(window.cutsceneSystem&&window.cutsceneSystem.active)return;
    if(M2.phase==='idle'&&window.M&&window.M.phase==='free'){M2.phase='trigger';missionMarker.x=M2_TRIGGER.x;missionMarker.y=M2_TRIGGER.y;missionMarker.active=true;missionMarker.kind='trigger2';showMission('📞 Новый звонок... найди маркер «2»',3500);}
    if(M2.phase==='trigger'&&missionMarker.active&&dist(player,missionMarker)<55){missionMarker.active=false;M2.phase='cutscene';playSFX('mission');window.cutsceneSystem.start(D2_START,()=>{resetM2();showMission('📋 Миссия: Зачистка склада',3000);});}
    if(M2.phase==='active'){
        if(M2.cur===0&&dist(player,M2_WARE)<60){M2.objectives[0].done=true;M2.cur=1;spawnM2(M2_WARE.x,M2_WARE.y);missionMarker.active=false;showMission('⚔️ Банда здесь! Убей всех!',2500);playSFX('select');}
        if(M2.cur===1){m2Enemies.forEach(e=>{if(!e.alive)return;const d=dist(e,player);e.angle=angleTo(e,player);if(d>165){e.x+=Math.cos(e.angle)*1.2;e.y+=Math.sin(e.angle)*1.2;}else if(d<110){e.x-=Math.cos(e.angle)*.8;e.y-=Math.sin(e.angle)*.8;}if(collidesBuilding(e.x,e.y,10)){e.x-=Math.cos(e.angle)*6;e.y-=Math.sin(e.angle)*6;}e.x=clamp(e.x,0,WORLD_W);e.y=clamp(e.y,0,WORLD_H);e.shootT--;if(d<330&&e.shootT<=0){e.shootT=55+rand(0,45);shoot(e.x+Math.cos(e.angle)*14,e.y+Math.sin(e.angle)*14,e.angle+rand(-.12,.12),7,300,'police');playSFX('shoot');}});
            for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];if(b.owner!=='player')continue;for(const e of m2Enemies){if(e.alive&&dist(b,e)<14){e.hp-=b.damage;spawnParticles(e.x,e.y,'#f00',4,2);playSFX('hit');bullets.splice(i,1);if(e.hp<=0){e.alive=false;addBlood(e.x,e.y);spawnParticles(e.x,e.y,'#a00',12,3);player.money+=20;}break;}}}
            const dead=m2Enemies.filter(e=>!e.alive).length;M2.objectives[1].text='Зачисти банду ('+dead+'/'+m2Enemies.length+')';
            if(dead>=m2Enemies.length){M2.objectives[1].done=true;M2.cur=2;missionMarker.x=M2_VICTOR.x;missionMarker.y=M2_VICTOR.y;missionMarker.active=true;missionMarker.kind='goal2b';showMission('✅ Район чист! Возвращайся к Виктору',2500);playSFX('select');}}
        if(M2.cur===2&&missionMarker.active&&dist(player,missionMarker)<55){M2.objectives[2].done=true;M2.phase='done';missionMarker.active=false;player.money+=M2.reward;playSFX('pickup');showMessage('МИССИЯ ВЫПОЛНЕНА!',3000);showMission('+$'+M2.reward,3000);m2Enemies.length=0;setTimeout(()=>window.cutsceneSystem.start(D2_DONE,()=>{M2.phase='free';}),3200);}}}
function renderMission2World(ctx,W,H){if(window.cutsceneSystem&&window.cutsceneSystem.active)return;
    if(M2.phase==='trigger'&&missionMarker.active){ctx.save();ctx.translate(-camera.x,-camera.y);const p=Math.sin(gameTime*.08)*5;ctx.strokeStyle='#f44';ctx.lineWidth=3;ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,45+p,0,6.28);ctx.stroke();ctx.globalAlpha=.12;ctx.fillStyle='#f44';ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,45+p,0,6.28);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#f44';ctx.font='bold 28px Arial';ctx.textAlign='center';ctx.fillText('2',missionMarker.x,missionMarker.y+10);if(dist(player,missionMarker)<120){ctx.fillStyle='#fff';ctx.font='14px Arial';ctx.fillText('Подойди ближе',missionMarker.x,missionMarker.y-55);}ctx.restore();arrow2(ctx,W,H,missionMarker.x,missionMarker.y);return;}
    if(M2.phase==='active'&&m2Enemies.length){ctx.save();ctx.translate(-camera.x,-camera.y);m2Enemies.forEach(e=>{if(!e.alive)return;ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.angle);ctx.fillStyle='#722';ctx.fillRect(-6,-5,12,10);ctx.fillStyle='#dba';ctx.beginPath();ctx.arc(7,0,6,0,6.28);ctx.fill();ctx.fillStyle='#222';ctx.beginPath();ctx.arc(7,0,6,-2.2,2.2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(10,-2,13,3);ctx.restore();ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(e.x-15,e.y-18,30,4);ctx.fillStyle='#f44';ctx.fillRect(e.x-15,e.y-18,30*(e.hp/e.maxHp),4);});if(M2.cur===1){const p=Math.sin(gameTime*.1)*4;ctx.strokeStyle='rgba(255,60,60,.5)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(M2_WARE.x,M2_WARE.y,130+p,0,6.28);ctx.stroke();}ctx.restore();}
    if(M2.phase==='active'&&missionMarker.active){ctx.save();ctx.translate(-camera.x,-camera.y);const p=Math.sin(gameTime*.08)*5;ctx.strokeStyle='#ff0';ctx.lineWidth=3;ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,50+p,0,6.28);ctx.stroke();ctx.globalAlpha=.1;ctx.fillStyle='#ff0';ctx.beginPath();ctx.arc(missionMarker.x,missionMarker.y,50+p,0,6.28);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#ff0';ctx.beginPath();ctx.moveTo(missionMarker.x,missionMarker.y-55-p);ctx.lineTo(missionMarker.x-10,missionMarker.y-70-p);ctx.lineTo(missionMarker.x+10,missionMarker.y-70-p);ctx.fill();const d=Math.round(dist(player,missionMarker));ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(d+'м',missionMarker.x,missionMarker.y-75-p);ctx.restore();arrow2(ctx,W,H,missionMarker.x,missionMarker.y);}}
function renderMission2HUD(ctx,W,H){if(M2.phase!=='active')return;const pX=W-330,pY=185,pW=310;ctx.fillStyle='rgba(0,0,0,.6)';ctx.fillRect(pX,pY,pW,30+M2.objectives.length*28);ctx.strokeStyle='rgba(255,60,60,.5)';ctx.lineWidth=1;ctx.strokeRect(pX,pY,pW,30+M2.objectives.length*28);ctx.fillStyle='#f44';ctx.font='bold 14px Arial';ctx.textAlign='left';ctx.fillText('🔫 Зачистка склада',pX+10,pY+20);M2.objectives.forEach((o,i)=>{const y=pY+45+i*28;if(o.done){ctx.fillStyle='#4c4';ctx.font='13px Arial';ctx.fillText('✅ '+o.text,pX+10,y);}else if(i===M2.cur){ctx.fillStyle='#ff0';ctx.font='bold 13px Arial';ctx.fillText('▶ '+o.text,pX+10,y);}else{ctx.fillStyle='#888';ctx.font='13px Arial';ctx.fillText('○ '+o.text,pX+10,y);}});}
const _u2=window.updateMission;window.updateMission=function(){if(_u2)_u2();updateMission2();};
const _r2=window.renderMissionHUD;window.renderMissionHUD=function(c,W,H){renderMission2World(c,W,H);if(_r2)_r2(c,W,H);renderMission2HUD(c,W,H);};
window.missionRestarters=window.missionRestarters||[];
window.missionRestarters.push(()=>{if(M2.phase==='active'){resetM2();showMission('🔁 Миссия 2 начата заново',2000);}});
window.M2=M2;window.m2Enemies=m2Enemies;